# 대구 버스 정류소 데이터 수집 파이프라인 - API 방식
- 공공 API로 대구 버스 정류소 데이터를 수집하고, 변환/검증 한 뒤 PostgreSQL과 CVS로 저장하기
- 국토교통부_(TAGO)_버스정류소정보

## 전체 파이프라인 흐름

1. 환경설정 : API 키 준비(.env), 기본 설정 준비
2. 수집 : JSON 구조 확인, 전체 페이지 수집
3. 판다스의 데이터프레임 만들기
4. 변환 : 데이터 확인, 컬럼명, 자료형
5. 파생컬럼(파생변수) 추가
6. 데이터 검증 (생략 가능)
7. DB 저장 : 먼저 pgAdmin에서 데이터베이스 만들기(busapidb) -> 테이블 저장 (bus_stop)
8. CSV 저장 : bus_stop.csv 인코딩 설정 (utf-8-sig)

### 라이브러리 불러오기

In [1]:
import math
import os
import time
from datetime import date
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

### API 키 불러오기

In [2]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

# 확인
if API_KEY:
    print(f'확인 {API_KEY[:6]}...{API_KEY[-4:]}')

확인 a82ec1...e8ad

### API 연결 테스트

In [3]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnNoList'

In [4]:
response = requests.get(BASE_URL, params={'serviceKey':API_KEY, '_type':'json'})
print(response.status_code) # 상태 확인

200

In [5]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getCtyCodeList'
response = requests.get(BASE_URL, params={'serviceKey':API_KEY, '_type':'json'})

response.json() # 대구는 22번

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'citycode': 12, 'cityname': '세종특별시'},
     {'citycode': 21, 'cityname': '부산광역시'},
     {'citycode': 22, 'cityname': '대구광역시'},
     {'citycode': 23, 'cityname': '인천광역시'},
     {'citycode': 24, 'cityname': '광주광역시'},
     {'citycode': 25, 'cityname': '대전광역시/계룡시'},
     {'citycode': 26, 'cityname': '울산광역시'},
     {'citycode': 39, 'cityname': '제주도'},
     {'citycode': 31010, 'cityname': '수원시'},
     {'citycode': 31020, 'cityname': '성남시'},
     {'citycode': 31030, 'cityname': '의정부시'},
     {'citycode': 31040, 'cityname': '안양시'},
     {'citycode': 31050, 'cityname': '부천시'},
     {'citycode': 31060, 'cityname': '광명시'},
     {'citycode': 31070, 'cityname': '평택시'},
     {'citycode': 31080, 'cityname': '동두천시'},
     {'citycode': 31090, 'cityname': '안산시'},
     {'citycode': 31100, 'cityname': '고양시'},
     {'citycode': 31110, 'cityname': '과천시'},
     {'citycode': 31120, 'cityname': '구리시'},
     {'citycode': 31130, 'cityname': '남양주시'},
     {'citycode': 31140, 'cityname': '오산시'},
     {'citycode': 31150, 'cityname': '시흥시'},
     {'citycode': 31160, 'cityname': '군포시'},
     {'citycode': 31170, 'cityname': '의왕시'},
     {'citycode': 31180, 'cityname': '하남시'},
     {'citycode': 31190, 'cityname': '용인시'},
     {'citycode': 31200, 'cityname': '파주시'},
     {'citycode': 31210, 'cityname': '이천시'},
     {'citycode': 31220, 'cityname': '안성시'},
     {'citycode': 31230, 'cityname': '김포시'},
     {'citycode': 31240, 'cityname': '화성시'},
     {'citycode': 31250, 'cityname': '광주시'},
     {'citycode': 31260, 'cityname': '양주시'},
     {'citycode': 31270, 'cityname': '포천시'},
     {'citycode': 31320, 'cityname': '여주시'},
     {'citycode': 31350, 'cityname': '연천군'},
     {'citycode': 31370, 'cityname': '가평군'},
     {'citycode': 31380, 'cityname': '양평군'},
     {'citycode': 32010, 'cityname': '춘천시'},
     {'citycode': 32020, 'cityname': '원주시/횡성군'},
     {'citycode': 32050, 'cityname': '태백시'},
     {'citycode': 32310, 'cityname': '홍천군'},
     {'citycode': 32360, 'cityname': '철원군'},
     {'citycode': 32410, 'cityname': '양양군'},
     {'citycode': 33010, 'cityname': '청주시'},
     {'citycode': 33020, 'cityname': '충주시'},
     {'citycode': 33030, 'cityname': '제천시'},
     {'citycode': 33320, 'cityname': '보은군'},
     {'citycode': 33330, 'cityname': '옥천군'},
     {'citycode': 33340, 'cityname': '영동군'},
     {'citycode': 33350, 'cityname': '진천군'},
     {'citycode': 33360, 'cityname': '괴산군'},
     {'citycode': 33370, 'cityname': '음성군'},
     {'citycode': 33380, 'cityname': '단양군'},
     {'citycode': 34010, 'cityname': '천안시'},
     {'citycode': 34020, 'cityname': '공주시'},
     {'citycode': 34030, 'cityname': '보령시'},
     {'citycode': 34040, 'cityname': '아산시'},
     {'citycode': 34050, 'cityname': '서산시'},
     {'citycode': 34060, 'cityname': '논산시'},
     {'citycode': 34070, 'cityname': '계룡시'},
     {'citycode': 34310, 'cityname': '금산군'},
     {'citycode': 34330, 'cityname': '부여군'},
     {'citycode': 34340, 'cityname': '서천군'},
     {'citycode': 34350, 'cityname': '청양군'},
     {'citycode': 34380, 'cityname': '태안군'},
     {'citycode': 34390, 'cityname': '당진시'},
     {'citycode': 35010, 'cityname': '전주시'},
     {'citycode': 35020, 'cityname': '군산시'},
     {'citycode': 35030, 'cityname': '익산시'},
     {'citycode': 35040, 'cityname': '정읍시'},
     {'citycode': 35050, 'cityname': '남원시'},
     {'citycode': 35060, 'cityname': '김제시'},
     {'citycode': 35320, 'cityname': '진안군'},
     {'citycode': 35330, 'cityname': '무주군'},
     {'citycode': 35340, 'cityname': '장수군'},
     {'citycode': 35350, 'cityname': '임실군'},
     {'citycode': 35360, 'cityname': '순창군'},
     {'citycode': 35370, 'cityname': '고창군'},
     {'citycode': 35380, 'cityname': '부안군'},
     {'citycode': 36010, 'cityname': '목포시'},
     {'citycode': 36020, 'cityname': '여수시'},
     {'citycode': 36030, 'cityname': '순천시'},
     {'citycode': 36040, 'cityname': '나주시'},
     {'citycode': 36060, 'cityname': '광양시'},
     {'citycode': 36320, 'cityname': '곡성군'},
     {'citycode': 36330, 'cityname': '구례군'},
     {'citycode': 36350, 'cityname': '고흥군'},
     {'citycode': 36380, 'cityname': '장흥군'},
     {'citycode': 36400, 'cityname': '해남군'},
     {'citycode': 36410, 'cityname': '영암군'},
     {'citycode': 36420, 'cityname': '무안군'},
     {'citycode': 36430, 'cityname': '함평군'},
     {'citycode': 36450, 'cityname': '장성군'},
     {'citycode': 36460, 'cityname': '완도군'},
     {'citycode': 36470, 'cityname': '진도군'},
     {'citycode': 36480, 'cityname': '신안군'},
     {'citycode': 37010, 'cityname': '포항시'},
     {'citycode': 37020, 'cityname': '경주시'},
     {'citycode': 37030, 'cityname': '김천시'},
     {'citycode': 37040, 'cityname': '안동시'},
     {'citycode': 37050, 'cityname': '구미시'},
     {'citycode': 37060, 'cityname': '영주시'},
     {'citycode': 37070, 'cityname': '영천시'},
     {'citycode': 37080, 'cityname': '상주시'},
     {'citycode': 37090, 'cityname': '문경시'},
     {'citycode': 37100, 'cityname': '경산시'},
     {'citycode': 37320, 'cityname': '의성군'},
     {'citycode': 37330, 'cityname': '청송군'},
     {'citycode': 37340, 'cityname': '영양군'},
     {'citycode': 37350, 'cityname': '영덕군'},
     {'citycode': 37360, 'cityname': '청도군'},
     {'citycode': 37370, 'cityname': '고령군'},
     {'citycode': 37380, 'cityname': '성주군'},
     {'citycode': 37390, 'cityname': '칠곡군'},
     {'citycode': 37400, 'cityname': '예천군'},
     {'citycode': 37410, 'cityname': '봉화군'},
     {'citycode': 37420, 'cityname': '울진군'},
     {'citycode': 37430, 'cityname': '울릉군'},
     {'citycode': 38010, 'cityname': '창원시'},
     {'citycode': 38030, 'cityname': '진주시'},
     {'citycode': 38050, 'cityname': '통영시'},
     {'citycode': 38060, 'cityname': '사천시'},
     {'citycode': 38070, 'cityname': '김해시'},
     {'citycode': 38080, 'cityname': '밀양시'},
     {'citycode': 38090, 'cityname': '거제시'},
     {'citycode': 38100, 'cityname': '양산시'},
     {'citycode': 38310, 'cityname': '의령군'},
     {'citycode': 38320, 'cityname': '함안군'},
     {'citycode': 38330, 'cityname': '창녕군'},
     {'citycode': 38340, 'cityname': '고성군'},
     {'citycode': 38350, 'cityname': '남해군'},
     {'citycode': 38360, 'cityname': '하동군'},
     {'citycode': 38370, 'cityname': '산청군'},
     {'citycode': 38380, 'cityname': '함양군'},
     {'citycode': 38390, 'cityname': '거창군'},
     {'citycode': 38400, 'cityname': '합천군'}]}}}}

In [6]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnNoList'
response = requests.get(BASE_URL, params={'serviceKey':API_KEY,'pageNo':1,'numOfRows':10, '_type':'json', 'cityCode':22})
print(response.status_code) # 상태 확인
data = response.json()

200

In [7]:
data['response']['body']['items']['item']

[{'gpslati': 35.84862,
  'gpslong': 128.51588,
  'nodeid': 'DGB7041046200',
  'nodenm': '이곡역(3번출구)',
  'nodeno': '00863'},
 {'gpslati': 35.85018,
  'gpslong': 128.52916,
  'nodeid': 'DGB7041046400',
  'nodenm': '용산역(6번출구)',
  'nodeno': '01133'},
 {'gpslati': '35.85200',
  'gpslong': 128.52718,
  'nodeid': 'DGB7041046600',
  'nodenm': '롯데캐슬그랜드',
  'nodeno': '01132'},
 {'gpslati': 35.85224,
  'gpslong': 128.52718,
  'nodeid': 'DGB7041046700',
  'nodenm': '대구지방법원서부지원',
  'nodeno': '01131'},
 {'gpslati': 35.85337,
  'gpslong': 128.52473,
  'nodeid': 'DGB7041046800',
  'nodenm': '달구벌종합복지관앞',
  'nodeno': '01128'},
 {'gpslati': '35.85320',
  'gpslong': 128.52467,
  'nodeid': 'DGB7041046900',
  'nodenm': '달구벌종합복지관건너',
  'nodeno': '01127'},
 {'gpslati': '35.85410',
  'gpslong': 128.52626,
  'nodeid': 'DGB7041047000',
  'nodenm': '장산초등학교앞',
  'nodeno': '09284'},
 {'gpslati': 35.85396,
  'gpslong': 128.52644,
  'nodeid': 'DGB7041047100',
  'nodenm': '장산초등학교건너',
  'nodeno': '01129'},
 {'gpslati': 35.85413,
  'gpslong': 128.52892,
  'nodeid': 'DGB7041047200',
  'nodenm': '1차서한화성타운앞',
  'nodeno': '01125'},
 {'gpslati': 35.84182,
  'gpslong': 128.53182,
  'nodeid': 'DGB7041047300',
  'nodenm': '달서에스케이뷰아파트(북편)',
  'nodeno': 20948}]

### 환경설정

In [8]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnNoList'
CITY_CODE = 22
ROWS_PER_PAGE = 1000
REQUEST_TIMEOUT = 10

### 저장 경로

In [9]:
BASE_DIR = os.getcwd() #현재 위치
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR,'bus_stop.csv')

### PostSQL 설정

In [10]:
DB_URL = 'postgresql://postgres:1234@Localhost:5432/busapidb'
TABLE_NAME = 'bus_stop'

print(f'csv 저장 경로 : {OUTPUT_PATH}')

csv 저장 경로 : c:\Users\Administrator\bigdata2026\fastapi\03_busapi_pipeline\output\bus_stop.csv

### 전체 데이터 수집
- 올림 math.ceil()

In [11]:
data['response']['body']['totalCount']

4259

In [12]:
total_count = data['response']['body']['totalCount']
total_pages = math.ceil(total_count/ ROWS_PER_PAGE)
print(f'{total_count:,}')
print(total_pages)

4,259
5

In [18]:
all_items = []

for page_no in range(1,total_pages+1):
    params={
        'serviceKey':API_KEY,
        'pageNo':page_no,
        'numOfRows':ROWS_PER_PAGE, 
        '_type':'json', 
        'cityCode':CITY_CODE
    }

    response = requests.get(BASE_URL, params=params, timeout=REQUEST_TIMEOUT)
    response.raise_for_status()

    page_body = response.json()['response']['body']

    # 마지막 페이지나 오류 상황에는 items가 비어 있을 수 있다.
    if not page_body.get('items'):
        print(f'{page_no} / {total_pages} 페이지: 페이지 없음')
        continue # 다음페이지로

    page_items = page_body['items'].get('item', []) # 없으면 빈 리스트

    if isinstance(page_items, dict):
        page_items = [page_items] # 딕셔너리가 맞다면 리스트 형태로 저장
    
    all_items.extend(page_items) # 여러개를 한꺼번에 추가

    print(f'{page_no} / {total_pages} 페이지 수집 완료 --> 누적 {len(all_items):,}건')

    time.sleep(0.2) # 너무 빠르지 않게 0.2초 기다린 후에 다음 진행

print(f'전체 수집 완료 {len(all_items):,}건')

1 / 5 페이지 수집 완료 --> 누적 1,000건
2 / 5 페이지 수집 완료 --> 누적 2,000건
3 / 5 페이지 수집 완료 --> 누적 3,000건
4 / 5 페이지 수집 완료 --> 누적 4,000건
5 / 5 페이지 수집 완료 --> 누적 4,259건
전체 수집 완료 4,259건

### DataFrame 만들기

In [19]:
df_raw = pd.DataFrame(all_items)

print(f'데이터프레임의  : {df_raw.shape}')
print(f'컬럼 목록 : {df_raw.columns.tolist()}')

데이터프레임의  : (4259, 5)
컬럼 목록 : ['gpslati', 'gpslong', 'nodeid', 'nodenm', 'nodeno']

In [20]:
df_raw.head()

    gpslati    gpslong         nodeid      nodenm nodeno
0  35.84862  128.51588  DGB7041046200   이곡역(3번출구)  00863
1  35.85018  128.52916  DGB7041046400   용산역(6번출구)  01133
2  35.85200  128.52718  DGB7041046600     롯데캐슬그랜드  01132
3  35.85224  128.52718  DGB7041046700  대구지방법원서부지원  01131
4  35.85337  128.52473  DGB7041046800   달구벌종합복지관앞  01128

In [21]:
df_raw.sample(5)

       gpslati    gpslong         nodeid         nodenm nodeno
490   35.88392  128.65680  DGB7011020700     금사리하이빌APT앞  01587
1800  35.84176  128.50715  DGB7041012400          금복주건너  21017
2781  35.86013  128.71669  DGB7061025400     안심교(반야월방향)  01664
3210  35.87755  128.41788  DGB7111029100        동곡초등학교앞  20876
3899  36.13688  128.80058  DGB7361000297  학성2리-용아-괴산-장곡  10297

### 컬럼명 정리
- 도시코드, 정류소 ID, 정류소명, 정류소번호, 위도, 경도
- citycode, nodeid, nodenm, nodeno, gpslati, gpslong

In [22]:
COLUMN_RENAME = {
    'citycode':'도시코드',
    'nodeid':'정류소ID', 
    'nodenm':'정류소명',
    'nodeno':'정류소번호',
    'gpslati':'위도',
    'gpslong':'경도'
}
df = df_raw.rename(columns=COLUMN_RENAME)

print(f'변경 후 컬럼 목록: {df.columns.to_list()}')

변경 후 컬럼 목록: ['위도', '경도', '정류소ID', '정류소명', '정류소번호']

In [23]:
df.sample(5)

            위도         경도          정류소ID      정류소명  정류소번호
3239  35.80755  128.49624  DGB7111036800       구라리  01720
2429  36.00490  128.55156  DGB7181002200      삼산건너  05746
117   35.81460  128.75140  DGB3600015500  사동초원파크 앞    NaN
1973  35.86093  128.52146  DGB7041030800   성곡중학교건너  01142
456   35.88979  128.64788  DGB7011017300  동촌화성타운건너  20620

### 자료형 변환
- 숫자처럼 보여도 문자열로 들어간 경우가 있다.
- 위도와 경도는 숫자로 변환 (pd.to_numeric() -> 바꿀 수 없으면 NaN)
- 정류소번호는 비어있는 경우가 많으므로 결측칠르 허용하는 int64 자료형 사용

In [ ]:
if '위도' in df.columns:
    df['위도'] = pd.to_numeric(df['위도'], errors='coerce')

if '경도' in df.columns:
    df['경도'] = pd.to_numeric(df['경도'], errors='coerce')

In [25]:
if '정류소번호' in df.columns:
    df['정류소번호'] = pd.to_numeric(df['정류소번호'], errors='coerce').astype('Int64')

In [26]:
df.dtypes

위도       float64
경도       float64
정류소ID        str
정류소명         str
정류소번호      Int64
dtype: object

### 파생 컬럼(파생 변수) 추가

- 수집일시 : 데이터를 수집할 날짜
- 위치구분 : 정류소명에 포함된 대구 행정구

In [28]:
# 수집 일시 추가

date.today()

datetime.date(2026, 7, 2)

In [29]:
df['수집일시'] = str(date.today())

In [30]:
df

            위도         경도          정류소ID        정류소명  정류소번호        수집일시
0     35.84862  128.51588  DGB7041046200   이곡역(3번출구)    863  2026-07-02
1     35.85018  128.52916  DGB7041046400   용산역(6번출구)   1133  2026-07-02
2     35.85200  128.52718  DGB7041046600     롯데캐슬그랜드   1132  2026-07-02
3     35.85224  128.52718  DGB7041046700  대구지방법원서부지원   1131  2026-07-02
4     35.85337  128.52473  DGB7041046800   달구벌종합복지관앞   1128  2026-07-02
...        ...        ...            ...         ...    ...         ...
4254  36.23677  128.68138  DGB7362000578        청로1리   <NA>  2026-07-02
4255  36.23455  128.68245  DGB7362000579        청로2리   <NA>  2026-07-02
4256  36.23992  128.64526  DGB7362000697        도경1리   <NA>  2026-07-02
4257  36.23678  128.68152  DGB7362000766        청로1리   <NA>  2026-07-02
4258  36.23459  128.68257  DGB7362000767        청로2리   <NA>  2026-07-02

[4259 rows x 6 columns]

### 대구 행정구 추가

In [31]:
gu_list = ['북구','중구','동구','서구','남구','수성구','달서군','달서구']

# 함수 정의
def get_gu(stop_name):
    """
    정류소명에 포함된 행정구를 찾아 반환하는 함수
    """
    stop_name = str(stop_name)

    for gu in gu_list:
        if gu in stop_name:
            return gu
    return '기타'

if '정류소명' in df.columns:
    df['위치구분'] = df['정류소명'].apply(get_gu)

In [32]:
df

            위도         경도          정류소ID        정류소명  정류소번호        수집일시 위치구분
0     35.84862  128.51588  DGB7041046200   이곡역(3번출구)    863  2026-07-02   기타
1     35.85018  128.52916  DGB7041046400   용산역(6번출구)   1133  2026-07-02   기타
2     35.85200  128.52718  DGB7041046600     롯데캐슬그랜드   1132  2026-07-02   기타
3     35.85224  128.52718  DGB7041046700  대구지방법원서부지원   1131  2026-07-02   기타
4     35.85337  128.52473  DGB7041046800   달구벌종합복지관앞   1128  2026-07-02   기타
...        ...        ...            ...         ...    ...         ...  ...
4254  36.23677  128.68138  DGB7362000578        청로1리   <NA>  2026-07-02   기타
4255  36.23455  128.68245  DGB7362000579        청로2리   <NA>  2026-07-02   기타
4256  36.23992  128.64526  DGB7362000697        도경1리   <NA>  2026-07-02   기타
4257  36.23678  128.68152  DGB7362000766        청로1리   <NA>  2026-07-02   기타
4258  36.23459  128.68257  DGB7362000767        청로2리   <NA>  2026-07-02   기타

[4259 rows x 7 columns]

### 위도 경도를 사용하여 좌표로 위치구분 파생 컬럼 만들기

In [33]:
# 대구 8개의 구, 군의 대략적인 중심좌표 설정
GU_CENTERS = {
    '북구':(35.8856,128.5894),
    '중구':(35.8694,128.6062),
    '동구':(35.8865,128.6355),
    '서구':(35.8718,128.5546),
    '남구':(35.8463,128.6001),
    '수성구':(35.8597,128.6310),
    '달서군':(35.7748,128.4313),
    '달서구':(35.8302,128.5323)
}

In [35]:
# 함수 정의 - 유클리드 거리: 두 좌표 사이의 제곱합의 루트
def get_gu_by_distance(lat,lon):
    if pd.isna(lat) or pd.isna(lon):
        return '기타'
    nearest_gu = None
    min_distance = None

    for gu, (gu_lat, gu_lon) in GU_CENTERS.items():
        distance = ((lat-gu_lat)**2 + (lon-gu_lon)**2)**0.5

        if min_distance is None or min_distance > distance:
            min_distance = distance
            nearest_gu = gu

    return nearest_gu

if '위도' in df.columns and '경도' in df.columns:
    df['위치구분'] = df.apply(
        lambda row: get_gu_by_distance(row['위도'],row['경도']),
        axis=1
    )

df

            위도         경도          정류소ID        정류소명  정류소번호        수집일시 위치구분
0     35.84862  128.51588  DGB7041046200   이곡역(3번출구)    863  2026-07-02  달서구
1     35.85018  128.52916  DGB7041046400   용산역(6번출구)   1133  2026-07-02  달서구
2     35.85200  128.52718  DGB7041046600     롯데캐슬그랜드   1132  2026-07-02  달서구
3     35.85224  128.52718  DGB7041046700  대구지방법원서부지원   1131  2026-07-02  달서구
4     35.85337  128.52473  DGB7041046800   달구벌종합복지관앞   1128  2026-07-02  달서구
...        ...        ...            ...         ...    ...         ...  ...
4254  36.23677  128.68138  DGB7362000578        청로1리   <NA>  2026-07-02   동구
4255  36.23455  128.68245  DGB7362000579        청로2리   <NA>  2026-07-02   동구
4256  36.23992  128.64526  DGB7362000697        도경1리   <NA>  2026-07-02   동구
4257  36.23678  128.68152  DGB7362000766        청로1리   <NA>  2026-07-02   동구
4258  36.23459  128.68257  DGB7362000767        청로2리   <NA>  2026-07-02   동구

[4259 rows x 7 columns]

In [36]:
df['위치구분'].value_counts()

위치구분
동구     1070
달서구     726
북구      721
달서군     453
수성구     421
서구      412
남구      329
중구      127
Name: count, dtype: int64

In [37]:
def save_to_postgresql(df, db_url, table_name):
    """
    DB 테이블로 저장
    """
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print(version[:80]+'...')

    # DATAFRAME을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize= 1000,
        method='multi',
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]
        print(saved_count)

In [38]:
save_to_postgresql(df, DB_URL, TABLE_NAME)

PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
4259

### CSV 저장

In [39]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

In [40]:
df.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)
print('저장 완료')

저장 완료

### 최종 결과 요약

In [41]:
print('='*80)
print('대구 버스 정류소 API 수집 파이프라인 결과')
print('='*80)
print(f'수집 방식 : 공공데이터포털 - TAGO REST API')
print(f'도시 코드 : {CITY_CODE} (대구)')
print(f'수집 건수 : {len(df):,}')
print(f'컬럼 수 : {len(df.columns)} 개')
print(f'수집 일시 : {df["수집일시"].iloc[0]}')
print(f'CSV 저장 위치 : {OUTPUT_PATH}')
print(f'DB 저장 위치 : busapidb.{TABLE_NAME}')

if '위치구분' in df.columns:
    print('-'*60)
    print('위치구분 상위 5개')
    print(df['위치구분'].value_counts().head())

if '위도' in df.columns and '경도' in df.columns:
    print('-'*60)
    print(f'위도 범위 : {df["위도"].min():.4f} ~ {df["위도"].max():.4f}')
    print(f'경도 범위 : {df["경도"].min():.4f} ~ {df["경도"].max():.4f}')

print('='*80)

================================================================================
대구 버스 정류소 API 수집 파이프라인 결과
================================================================================
수집 방식 : 공공데이터포털 - TAGO REST API
도시 코드 : 22 (대구)
수집 건수 : 4,259
컬럼 수 : 7 개
수집 일시 : 2026-07-02
CSV 저장 위치 : c:\Users\Administrator\bigdata2026\fastapi\03_busapi_pipeline\output\bus_stop.csv
DB 저장 위치 : busapidb.bus_stop
------------------------------------------------------------
위치구분 상위 5개
위치구분
동구     1070
달서구     726
북구      721
달서군     453
수성구     421
Name: count, dtype: int64
------------------------------------------------------------
위도 범위 : 35.6173 ~ 36.3124
경도 범위 : 128.3582 ~ 128.8804
================================================================================