In [4]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

# 경로설정
# getcwd()-> 파일 위치나 폴더 위치를 가져온다.
BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\01_subway_pipeline'

In [5]:
DATA_PATH = os.path.join(BASE_DIR,'input', 'subway_raw.csv')
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\01_subway_pipeline\\input\\subway_raw.csv'

In [6]:
OUTPUT_PATH = os.path.join(BASE_DIR,'output','subway_long.csv')

In [7]:
# DB 연결
DB_URL = 'postgresql://postgres:1234@localhost:5432/subwaydb'

In [8]:
WEEKDAY_NAMES = {0:'월',1:'화',2:'수',3:'목',4:'금',5:'토',6:'일'}

In [9]:
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw

,월,일,역번호,역명,승하,05시-06시,06시-07시,07시-08시,08시-09시,09시-10시,...,15시-16시,16시-17시,17시-18시,18시-19시,19시-20시,20시-21시,21시-22시,22시-23시,23시-24시,일계
0,1,1,1150,설화명곡,승차,22,37,61,111,167,...,270,216,192,138,125,87,56,47,7,2867
1,1,1,1150,설화명곡,하차,1,65,38,68,79,...,166,163,183,217,194,126,152,116,69,2177
2,1,1,1160,화원,승차,15,25,54,102,144,...,225,195,218,135,90,66,50,28,13,2416
3,1,1,1160,화원,하차,1,42,50,48,85,...,228,212,221,169,159,129,151,121,95,2377
4,1,1,1170,대곡,승차,46,57,86,137,243,...,354,323,351,215,128,129,101,60,11,4009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66425,12,31,3390,지산,하차,14,25,17,31,44,...,101,95,161,124,108,55,68,68,96,1368
66426,12,31,3400,범물,승차,30,35,46,95,154,...,270,229,224,199,154,128,140,130,81,2981
66427,12,31,3400,범물,하차,18,24,23,43,86,...,205,249,254,241,195,144,131,141,219,2759
66428,12,31,3410,용지,승차,11,19,36,87,146,...,145,113,118,114,66,36,34,47,19,1723
66429,12,31,3410,용지,하차,9,39,32,45,66,...,159,127,117,153,73,81,69,46,79,1566

In [7]:
df_raw.shape

(66430, 25)

In [8]:
for i, col in enumerate(df_raw.columns):
    print(f'[{i}] {col}')

[0] 월
[1] 일
[2] 역번호
[3] 역명
[4] 승하
[5] 05시-06시
[6] 06시-07시
[7] 07시-08시
[8] 08시-09시
[9] 09시-10시
[10] 10시-11시
[11] 11시-12시
[12] 12시-13시
[13] 13시-14시
[14] 14시-15시
[15] 15시-16시
[16] 16시-17시
[17] 17시-18시
[18] 18시-19시
[19] 19시-20시
[20] 20시-21시
[21] 21시-22시
[22] 22시-23시
[23] 23시-24시
[24] 일계

In [9]:
df_raw.dtypes

월          int64
일          int64
역번호        int64
역명           str
승하           str
05시-06시    int64
06시-07시    int64
07시-08시    int64
08시-09시    int64
09시-10시    int64
10시-11시    int64
11시-12시    int64
12시-13시    int64
13시-14시    int64
14시-15시    int64
15시-16시    int64
16시-17시    int64
17시-18시    int64
18시-19시    int64
19시-20시    int64
20시-21시    int64
21시-22시    int64
22시-23시    int64
23시-24시    int64
일계         int64
dtype: object

In [13]:
# 결측치 확인
null_counts = df_raw.isnull().sum()
if null_counts.any():
    print('결측치 발견')
    print(null_counts[null_counts>0])
else:
    print('결측치 없음')

결측치 없음

In [14]:
id_cols = ['월', '일', '역번호','역명','승하']
time_cols = [c for c in df_raw.columns if '시' in c]
print(f'시간대별 컬럼 수 {len(time_cols)}')
print(f'시간대별 컬럼 목록 : {time_cols}')

시간대별 컬럼 수 19
시간대별 컬럼 목록 : ['05시-06시', '06시-07시', '07시-08시', '08시-09시', '09시-10시', '10시-11시', '11시-12시', '12시-13시', '13시-14시', '14시-15시', '15시-16시', '16시-17시', '17시-18시', '18시-19시', '19시-20시', '20시-21시', '21시-22시', '22시-23시', '23시-24시']

## pd.melt() --> wide를 long으로 변환

In [ ]:
df_long = pd.melt(
    df_raw,
    id_vars=id_cols, # 유지할 열
    value_vars=time_cols, # 행으로 만들 열
    var_name='시간대컬럼', # 새 열의 이름
    value_name='인원수', # 값을 담을 새 열의 이름
)

df_long = df_long.reset_index(drop=True)

In [17]:
df_long.head()

   월  일   역번호    역명  승하    시간대컬럼  인원수
0  1  1  1150  설화명곡  승차  05시-06시   22
1  1  1  1150  설화명곡  하차  05시-06시    1
2  1  1  1160    화원  승차  05시-06시   15
3  1  1  1160    화원  하차  05시-06시    1
4  1  1  1170    대곡  승차  05시-06시   46

## 파생컬럼(파생변수)
### 정규표형식으로 숫자 추출
r'^(\d+)시'
- ^ :문자열 맨 앞
- (\d+): 숫자 하나 이상
- 시 : 시 글자

ex) 05 시 == 5(int로 형 변환)

In [19]:
# 시작시 컬럼 추가
# 05~06 앞에 숫자만 추출-> 정수 변환

df_long['시작시'] = df_long['시간대컬럼'].str.extract(r'^(\d+)시')
df_long['시작시']

0          05
1          05
2          05
3          05
4          05
           ..
1262165    23
1262166    23
1262167    23
1262168    23
1262169    23
Name: 시작시, Length: 1262170, dtype: str

In [20]:
type(df_long['시작시'])

pandas.Series

In [21]:
df_long['시작시'][0]

'05'

In [24]:
df_long['시작시'] = df_long['시작시'].astype('int')

In [25]:
df_long.head()

   월  일   역번호    역명  승하    시간대컬럼  인원수  시작시
0  1  1  1150  설화명곡  승차  05시-06시   22    5
1  1  1  1150  설화명곡  하차  05시-06시    1    5
2  1  1  1160    화원  승차  05시-06시   15    5
3  1  1  1160    화원  하차  05시-06시    1    5
4  1  1  1170    대곡  승차  05시-06시   46    5

In [28]:
# 날짜 컬럼 추가
YEAR = 2026

# pd.to_datetime(dict)
# 연월일 딕셔너리를 한번에 datetime으로 변환

df_series = pd.to_datetime(
    dict(year=YEAR, month=df_long['월'], day=df_long['일'])
)

df_series.dt.date

0          2026-01-01
1          2026-01-01
2          2026-01-01
3          2026-01-01
4          2026-01-01
              ...
1262165    2026-12-31
1262166    2026-12-31
1262167    2026-12-31
1262168    2026-12-31
1262169    2026-12-31
Length: 1262170, dtype: object

In [29]:
df_long['날짜'] = df_series.dt.date
df_long.head()

   월  일   역번호    역명  승하    시간대컬럼  인원수  시작시          날짜
0  1  1  1150  설화명곡  승차  05시-06시   22    5  2026-01-01
1  1  1  1150  설화명곡  하차  05시-06시    1    5  2026-01-01
2  1  1  1160    화원  승차  05시-06시   15    5  2026-01-01
3  1  1  1160    화원  하차  05시-06시    1    5  2026-01-01
4  1  1  1170    대곡  승차  05시-06시   46    5  2026-01-01

In [32]:
# 요일 코드 컬럼 추가

df_series.dt.weekday

0          3
1          3
2          3
3          3
4          3
          ..
1262165    3
1262166    3
1262167    3
1262168    3
1262169    3
Length: 1262170, dtype: int32

In [35]:
# .map(WEEKDAY_NAMES)
df_long['요일'] = df_series.dt.weekday.map(WEEKDAY_NAMES)
df_long

          월   일   역번호    역명  승하    시간대컬럼  인원수  시작시          날짜 요일
0         1   1  1150  설화명곡  승차  05시-06시   22    5  2026-01-01  목
1         1   1  1150  설화명곡  하차  05시-06시    1    5  2026-01-01  목
2         1   1  1160    화원  승차  05시-06시   15    5  2026-01-01  목
3         1   1  1160    화원  하차  05시-06시    1    5  2026-01-01  목
4         1   1  1170    대곡  승차  05시-06시   46    5  2026-01-01  목
...      ..  ..   ...   ...  ..      ...  ...  ...         ... ..
1262165  12  31  3390    지산  하차  23시-24시   96   23  2026-12-31  목
1262166  12  31  3400    범물  승차  23시-24시   81   23  2026-12-31  목
1262167  12  31  3400    범물  하차  23시-24시  219   23  2026-12-31  목
1262168  12  31  3410    용지  승차  23시-24시   19   23  2026-12-31  목
1262169  12  31  3410    용지  하차  23시-24시   79   23  2026-12-31  목

[1262170 rows x 10 columns]

In [36]:
# 주말 여부 확인
# 토(5), 일(6) 이면 True
df_long['주말'] = df_series.dt.weekday >= 5
df_long

          월   일   역번호    역명  승하    시간대컬럼  인원수  시작시          날짜 요일     주말
0         1   1  1150  설화명곡  승차  05시-06시   22    5  2026-01-01  목  False
1         1   1  1150  설화명곡  하차  05시-06시    1    5  2026-01-01  목  False
2         1   1  1160    화원  승차  05시-06시   15    5  2026-01-01  목  False
3         1   1  1160    화원  하차  05시-06시    1    5  2026-01-01  목  False
4         1   1  1170    대곡  승차  05시-06시   46    5  2026-01-01  목  False
...      ..  ..   ...   ...  ..      ...  ...  ...         ... ..    ...
1262165  12  31  3390    지산  하차  23시-24시   96   23  2026-12-31  목  False
1262166  12  31  3400    범물  승차  23시-24시   81   23  2026-12-31  목  False
1262167  12  31  3400    범물  하차  23시-24시  219   23  2026-12-31  목  False
1262168  12  31  3410    용지  승차  23시-24시   19   23  2026-12-31  목  False
1262169  12  31  3410    용지  하차  23시-24시   79   23  2026-12-31  목  False

[1262170 rows x 11 columns]

In [37]:
# 최종 컬럼의 목록
df_long.columns

Index(['월', '일', '역번호', '역명', '승하', '시간대컬럼', '인원수', '시작시', '날짜', '요일', '주말'], dtype='str')

In [38]:
df_long.columns.tolist()

['월', '일', '역번호', '역명', '승하', '시간대컬럼', '인원수', '시작시', '날짜', '요일', '주말']

In [39]:
df_long.dtypes

월         int64
일         int64
역번호       int64
역명          str
승하          str
시간대컬럼       str
인원수       int64
시작시       int64
날짜       object
요일          str
주말         bool
dtype: object

## PostgreSQL 저장

1. PostgreSQL 서버가 실행중인지 확인
2. subwaydb 데이터 베이스가 있는지 확인
3. DB_URL 의 비밀번호가 맞는지 확인

In [44]:
# 함수 정의
def save_to_postgresql(df, db_url, table_name):
    """
    데이터프레임을 PostgreSQL에 테이블로 저장
    """
    df_save = df.copy()

    # pandas 버전 차이에 따라 문자열 컬럼을 str로 정리
    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str) # 문자열로 변경
    
    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('Postgre 연결 성공')
        print(version[:80]+'...')

    # 데이터프레임을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi',
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]
    
    print(f'저장 완료{saved_count:,}행')
    print(f'DB : subwaydb / table {table_name}')

In [45]:
TABLE_NAME = 'subway_raw'

In [46]:
# 함수 호출
save_to_postgresql(df_long,DB_URL, TABLE_NAME)

Postgre 연결 성공
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료1,262,170행
DB : subwaydb / table subway_raw

## CVS 저장
- utf-8-sig

In [47]:
df_long.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)
print('CSV 저장 완료')
print(f'경로 : {OUTPUT_PATH}')
print(f'크기: {len(df_long):,}행 X {len(df_long.columns)}열')

CSV 저장 완료
경로 : c:\Users\Administrator\bigdata2026\fastapi\01_subway_pipeline\output\subway_long.csv
크기: 1,262,170행 X 11열